{{- $fullName := include "comentario.fullname" . -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-certificates
spec:
  secretName: {{ $fullName }}-cert-secret
  dnsNames:
    - {{ .Values.ingress.host }}
  subject:
    organizations:
      - Yktoo Solutions
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.clusterIssuer }}
