env:
  es6: true
globals:
  $: true
rules:
  no-bitwise: 2
  camelcase: 2
  brace-style:
  - error
  - 1tbs
  curly:
  - error
  - all
  eqeqeq:
  - error
  - smart
  indent:
  - error
  - 4
  no-use-before-define:
  - error
  - functions: false
  new-cap: error
  no-caller: error
  no-unused-vars: error
  prefer-template: error
  quote-props:
  - error
  - as-needed
  quotes:
  - error
  - single
  strict:
  - error
  - function
