env:
  es6: true
globals:
  $: true
rules:
  no-bitwise: 2
  camelcase: 2
  brace-style:
  - error
  - 1tbs
  curly:
  - error
  - all
  eqeqeq:
  - error
  - smart
  indent:
  - error
  - 4
  no-use-before-define:
  - 2
  - functions: false
  new-cap: 2
  no-caller: 2
  quotes:
  - 2
  - single
  no-unused-vars: 2
  strict:
  - 2
  - function
