# It's our root config
root: true

env:
  es6: true

rules:
  no-bitwise: 2
  camelcase: 2
  brace-style:
    - error
    - 1tbs
  curly:
    - error
    - all
  eqeqeq:
    - error
    - smart
  indent:
    - error
    - 4
    - SwitchCase: 1
  no-use-before-define:
    - error
    - functions: false
  new-cap: error
  no-caller: error
  no-unused-vars: error
  prefer-template: error
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - always
  strict:
    - error
    - function

overrides:
  # Gulp
  - files: gulpfile.js
    parserOptions:
      sourceType: module
    rules:
      strict: off
      camelcase: off

  # JavaScript files
  - files: '*.js'
    globals:
      $: true

  # TypeScript files
  - files: '*.ts'
    excludedFiles: 'cypress/**'
    parser: '@typescript-eslint/parser'
    plugins:
      - '@typescript-eslint'
    extends:
      - 'eslint:recommended'
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
    rules:
      '@typescript-eslint/no-use-before-define':
        - warn
        - ignoreTypeReferences: true
      '@typescript-eslint/no-explicit-any': off
      no-use-before-define: off # Replaced by @typescript-eslint/no-use-before-define
      object-shorthand: error

  # Cypress Typescript
  - files: cypress/**/*.ts
    extends:
      - 'plugin:cypress/recommended'
    rules: {}
