version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: comentario_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
