version: '3'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: comentario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # Transient data volume
      - type: tmpfs
        target: /var/lib/postgresql/data

  http:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - $PWD/etc/comment-test:/usr/share/nginx/html:ro
