version: '3'

services:
  server:
    image: comentario
    build:
      context: .
      args:
        RELEASE: prod
    environment:
      COMMENTO_ORIGIN: http://localhost:8080
      COMMENTO_PORT: 8080
      COMMENTO_POSTGRES: postgres://postgres:postgres@db:5432/commento?sslmode=disable

      # Dummy data for testing
      COMMENTO_GITHUB_KEY: a
      COMMENTO_GITHUB_SECRET: b
      COMMENTO_GITLAB_KEY: a
      COMMENTO_GITLAB_SECRET: b
      COMMENTO_GOOGLE_KEY: a
      COMMENTO_GOOGLE_SECRET: b
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - comentario_network

  db:
    image: postgres:11
    environment:
      POSTGRES_DB: commento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - comentario_network
    volumes:
      # Transient data volume
      - type: tmpfs
        target: /var/lib/postgresql/data
      # Initial DB seed
      - $PWD/etc/db-seed:/docker-entrypoint-initdb.d:ro

  http:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - $PWD/etc/comment-test:/usr/share/nginx/html:ro

networks:
  comentario_network:
