#!/bin/bash
#=======================================================================================================================
# Build and start the Comentario backend in the end-2-end testing mode
#=======================================================================================================================

set -e

root_dir="$(dirname "$(dirname "$(realpath "$0")")")"
build_dir="$root_dir/build"

# Show usage info and exit
usage() {
    cat <<EOF >&2
Usage: $0 [options] [[--] backend_args]
Options:
  -B  skip build
  -D  skip (re)starting database
  -G  skip OpenAPI code generation
  -h  show usage info and exit
EOF
    exit 0
}

# Parse the command line
declare -i do_build=1 do_db=1 do_gen=1
args=$(getopt -o BDGh -- "$@")
[[ $? -ne 0 ]] && usage
eval set -- $args
for i; do
    case "$i" in
        -B)
            do_build=0
            shift
            ;;
        -D)
            do_db=0
            shift
            ;;
        -G)
            do_gen=0
            shift
            ;;
        -h)
            usage
            ;;
        --)
            shift;
            break
            ;;
    esac
done

# Make sure destination dir exists
mkdir -p "$build_dir"

# Remove any leftovers from previous builds
rm -rf "$build_dir/db" "$build_dir/templates"

# Build the backend
((do_gen))   && go generate
((do_build)) &&
    rm -f "$build_dir/comentario" &&
    go build -o "$build_dir/comentario" -ldflags "-X main.version=$(git describe --tags) -X main.date=$(date --iso-8601=seconds)"

# (Re)start the database
if ((do_db)); then
    docker-compose -f "$root_dir/docker-compose.yml" down -v
    docker-compose -f "$root_dir/docker-compose.yml" up -d -- db http
fi

# Copy required assets
echo "Copying assets to $build_dir"
cp -r "$root_dir/db/" "$root_dir/templates/" "$build_dir"

# Use the (local) ~secrets.yaml file if it's present, otherwise the "stock" secrets.yaml
secrets="$root_dir/k8s/~secrets.yaml"
[[ ! -f "$secrets" ]] && secrets="$root_dir/k8s/secrets.yaml"
echo "Using secrets file: $secrets"

# Start the backend
echo "Starting $build_dir/comentario"
"$build_dir/comentario" \
    -vv \
    --port=8080 \
    --static-path="$build_dir" \
    --db-migration-path="$build_dir/db" \
    --template-path="$build_dir/templates" \
    --secrets="$secrets"
