package util

import (
	"errors"
)

var (
	ErrorBadCommentoExportVersion = errors.New("unsupported Commento export format version")
	ErrorCannotDeleteOwner        = errors.New("you cannot delete your account until all domains associated with your account are deleted")
	ErrorCannotUpdateOauthProfile = errors.New("you cannot update the profile of an external account managed by third-party log in. Please use the appropriate platform to update your details")
	ErrorCommentDeleted           = errors.New("this comment has been deleted")
	ErrorDatabaseMigration        = errors.New("encountered error applying database migration")
	ErrorDomainFrozen             = errors.New("cannot add a new comment because that domain is frozen")
	ErrorEmailAlreadyExists       = errors.New("that email address has already been registered")
	ErrorInternal                 = errors.New("an internal error has occurred. If you see this repeatedly, please contact support")
	ErrorInvalidAction            = errors.New("invalid action")
	ErrorInvalidDomainHost        = errors.New("invalid domain name; it must be a 'host' or 'host:port' value")
	ErrorInvalidDomainURL         = errors.New("invalid input; provide a valid domain name or a complete URL")
	ErrorInvalidEmailPassword     = errors.New("invalid email/password combination")
	ErrorMalformedTemplate        = errors.New("a template is malformed")
	ErrorMissingConfig            = errors.New("missing config environment variable")
	ErrorMissingField             = errors.New("one or more field(s) empty")
	ErrorNewOwnerForbidden        = errors.New("new owner registration is disabled")
	ErrorNoDisqusURL              = errors.New("export file must be hosted on disqus.com")
	ErrorNotDomainOwner           = errors.New("you need to be a domain owner to do that")
	ErrorNotModerator             = errors.New("you need to be a moderator to do that")
	ErrorOAuthNotConfigured       = errors.New("OAuth is not configured for this identity provider")
	ErrorPageLocked               = errors.New("unable to add comment: the page is locked")
	ErrorSelfVote                 = errors.New("you cannot vote on your own comment")
	ErrorSMTPNotConfigured        = errors.New("SMTP is not configured")
	ErrorSSOURLMissing            = errors.New("SSO URL is missing")
	ErrorUnauthenticated          = errors.New("you have to be authenticated in order to do that")
	ErrorUnconfirmedEmail         = errors.New("your email address is still unconfirmed. Please confirm your email address before proceeding")
	ErrorUnknownIdP               = errors.New("unknown identity provider")
)
