package util

import (
	"errors"
)

var (
	ErrorMalformedTemplate                  = errors.New("a template is malformed")
	ErrorMissingConfig                      = errors.New("missing config environment variable")
	ErrorCannotSendEmail                    = errors.New("email dispatch failed. Please contact support to resolve this issue")
	ErrorInternal                           = errors.New("an internal error has occurred. If you see this repeatedly, please contact support")
	ErrorInvalidJSONBody                    = errors.New("invalid JSON request. If you think this shouldn't happen, please contact support")
	ErrorMissingField                       = errors.New("one or more field(s) empty")
	ErrorEmailExists                        = errors.New("that email address is already registered. Sign in instead")
	ErrorInvalidEmailPassword               = errors.New("invalid email/password combination")
	ErrorUnconfirmedEmail                   = errors.New("your email address is still unconfirmed. Please confirm your email address before proceeding")
	ErrorNoSuchConfirmationToken            = errors.New("this email confirmation link has expired")
	ErrorNoSuchResetToken                   = errors.New("this password reset link has expired")
	ErrorNotAuthorised                      = errors.New("you're not authorised to access that")
	ErrorEmailAlreadyExists                 = errors.New("that email address has already been registered")
	ErrorNoSuchToken                        = errors.New("no such session token")
	ErrorNoSuchCommenter                    = errors.New("no such commenter")
	ErrorAlreadyUpvoted                     = errors.New("you have already upvoted that comment")
	ErrorNoSuchDomain                       = errors.New("this domain is not registered with Comentario")
	ErrorNoSuchComment                      = errors.New("no such comment")
	ErrorInvalidState                       = errors.New("invalid state value")
	ErrorDomainFrozen                       = errors.New("cannot add a new comment because that domain is frozen")
	ErrorDomainAlreadyExists                = errors.New("that domain has already been registered. Please contact support if you are the true owner")
	ErrorUnauthorisedVote                   = errors.New("you need to be authenticated to vote")
	ErrorNoSuchEmail                        = errors.New("no such email")
	ErrorInvalidEmail                       = errors.New("you do not have an email registered with that account")
	ErrorForbiddenEdit                      = errors.New("you cannot edit someone else's comment")
	ErrorMissingSmtpAddress                 = errors.New("missing SMTP_FROM_ADDRESS")
	ErrorSmtpNotConfigured                  = errors.New("SMTP is not configured")
	ErrorOauthMisconfigured                 = errors.New("OAuth is misconfigured")
	ErrorCannotReadResponse                 = errors.New("cannot read response")
	ErrorNotModerator                       = errors.New("you need to be a moderator to do that")
	ErrorNotADirectory                      = errors.New("the given path is not a directory")
	ErrorGzip                               = errors.New("cannot GZip content")
	ErrorCannotDownloadDisqus               = errors.New("we could not download your Disqus export file")
	ErrorCannotDownloadCommento             = errors.New("we could not download your Comentario export file")
	ErrorSelfVote                           = errors.New("you cannot vote on your own comment")
	ErrorInvalidConfigFile                  = errors.New("invalid config file")
	ErrorInvalidConfigValue                 = errors.New("invalid config value")
	ErrorNewOwnerForbidden                  = errors.New("new user registrations are forbidden and closed")
	ErrorThreadLocked                       = errors.New("this thread is locked. You cannot add new comments")
	ErrorDatabaseMigration                  = errors.New("encountered error applying database migration")
	ErrorNoSuchUnsubscribeSecretHex         = errors.New("invalid unsubscribe link")
	ErrorEmptyPaths                         = errors.New("empty paths field")
	ErrorInvalidDomain                      = errors.New("invalid domain name. Do not include the URL path after the forward slash")
	ErrorInvalidEntity                      = errors.New("that entity does not exist")
	ErrorCannotDeleteOwnerWithActiveDomains = errors.New("you cannot delete your account until all domains associated with your account are deleted")
	ErrorNoSuchOwner                        = errors.New("no such owner")
	ErrorCannotUpdateOauthProfile           = errors.New("you cannot update the profile of an external account managed by third-party log in. Please use the appropriate platform to update your details")
	ErrorUnsupportedCommentoImportVersion   = errors.New("unsupported Comentario import format version")
	ErrorInvalidAction                      = errors.New("invalid action")
)
