package main

import (
	"errors"
)

var errorMalformedTemplate = errors.New("a template is malformed")
var errorMissingConfig = errors.New("missing config environment variable")
var errorCannotSendEmail = errors.New("email dispatch failed. Please contact support to resolve this issue")
var errorInternal = errors.New("an internal error has occurred. If you see this repeatedly, please contact support")
var errorInvalidJSONBody = errors.New("invalid JSON request. If you think this shouldn't happen, please contact support")
var errorMissingField = errors.New("one or more field(s) empty")
var errorEmailExists = errors.New("that email address is already registered. Sign in instead")
var errorInvalidEmailPassword = errors.New("invalid email/password combination")
var errorUnconfirmedEmail = errors.New("your email address is still unconfirmed. Please confirm your email address before proceeding")
var errorNoSuchConfirmationToken = errors.New("this email confirmation link has expired")
var errorNoSuchResetToken = errors.New("this password reset link has expired")
var errorNotAuthorised = errors.New("you're not authorised to access that")
var errorEmailAlreadyExists = errors.New("that email address has already been registered")
var errorNoSuchToken = errors.New("no such session token")
var errorNoSuchCommenter = errors.New("no such commenter")
var errorAlreadyUpvoted = errors.New("you have already upvoted that comment")
var errorNoSuchDomain = errors.New("this domain is not registered with Comentario")
var errorNoSuchComment = errors.New("no such comment")
var errorInvalidState = errors.New("invalid state value")
var errorDomainFrozen = errors.New("cannot add a new comment because that domain is frozen")
var errorDomainAlreadyExists = errors.New("that domain has already been registered. Please contact support if you are the true owner")
var errorUnauthorisedVote = errors.New("you need to be authenticated to vote")
var errorNoSuchEmail = errors.New("no such email")
var errorInvalidEmail = errors.New("you do not have an email registered with that account")
var errorForbiddenEdit = errors.New("you cannot edit someone else's comment")
var errorMissingSmtpAddress = errors.New("missing SMTP_FROM_ADDRESS")
var errorSmtpNotConfigured = errors.New("SMTP is not configured")
var errorOauthMisconfigured = errors.New("OAuth is misconfigured")
var errorCannotReadResponse = errors.New("cannot read response")
var errorNotModerator = errors.New("you need to be a moderator to do that")
var errorNotADirectory = errors.New("the given path is not a directory")
var errorGzip = errors.New("cannot GZip content")
var errorCannotDownloadDisqus = errors.New("we could not download your Disqus export file")
var errorCannotDownloadCommento = errors.New("we could not download your Comentario export file")
var errorSelfVote = errors.New("you cannot vote on your own comment")
var errorInvalidConfigFile = errors.New("invalid config file")
var errorInvalidConfigValue = errors.New("invalid config value")
var errorNewOwnerForbidden = errors.New("new user registrations are forbidden and closed")
var errorThreadLocked = errors.New("this thread is locked. You cannot add new comments")
var errorDatabaseMigration = errors.New("encountered error applying database migration")
var errorNoSuchUnsubscribeSecretHex = errors.New("invalid unsubscribe link")
var errorEmptyPaths = errors.New("empty paths field")
var errorInvalidDomain = errors.New("invalid domain name. Do not include the URL path after the forward slash")
var errorInvalidEntity = errors.New("that entity does not exist")
var errorCannotDeleteOwnerWithActiveDomains = errors.New("you cannot delete your account until all domains associated with your account are deleted")
var errorNoSuchOwner = errors.New("no such owner")
var errorCannotUpdateOauthProfile = errors.New("you cannot update the profile of an external account managed by third-party log in. Please use the appropriate platform to update your details")
var errorUnsupportedCommentoImportVersion = errors.New("unsupported Comentario import format version")
var errorInvalidAction = errors.New("invalid action")
